from enum import StrEnum


class Intent(StrEnum):
    GENERAL_CHAT = "GENERAL_CHAT"
    PAGE_QA = "PAGE_QA"
    SELECTION_QA = "SELECTION_QA"
    VISUAL_QA = "VISUAL_QA"
    DOCUMENT_SEARCH = "DOCUMENT_SEARCH"
    FIND_LOCATION = "FIND_LOCATION"
    SUMMARY = "SUMMARY"
    QUIZ = "QUIZ"
    FLASHCARD = "FLASHCARD"
    COMPARE = "COMPARE"
    CLARIFY = "CLARIFY"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
